In [2]:
# https://github.com/pkbcz/MSW2

import numpy as np

In [3]:
# NumPy rozšiřuje Python o další datové typy.
for type in np.ScalarType:
    print(type)

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>
<class 'bytes'>
<class 'str'>
<class 'memoryview'>
<class 'numpy.bool_'>
<class 'numpy.complex64'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.longdouble'>
<class 'numpy.int8'>
<class 'numpy.int16'>
<class 'numpy.intc'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.datetime64'>
<class 'numpy.timedelta64'>
<class 'numpy.object_'>
<class 'numpy.bytes_'>
<class 'numpy.str_'>
<class 'numpy.uint8'>
<class 'numpy.uint16'>
<class 'numpy.uintc'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.void'>


In [6]:
vector = np.array([1, 2, 3, 4])
display(vector)

multidimensional_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
display(multidimensional_array)

array([1, 2, 3, 4])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
import sys

multidimensional_array_normal = list(range(0, 100))
multidimensional_array_numpy = np.array(multidimensional_array_normal)

print(
    f"multidimensional_array_normal: {sys.getsizeof(multidimensional_array_normal)} B"
)
print(f"multidimensional_array_numpy: {sys.getsizeof(multidimensional_array_numpy)} B")

multidimensional_array_normal: 856 B
multidimensional_array_numpy: 512 B


In [21]:
cube = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

display(cube)
display(cube - 1)  # odečítání skalárů
display(cube + 1)  # odečítání skalárů
display(-(cube - 1))  # změna znamínek
display(cube * 2)  # násobení skalárem
display(cube / 2)  # dělení skalárem (float)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

array([[ 0, -1, -2],
       [-3, -4, -5],
       [-6, -7, -8]])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [33]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])

display(a1)
display(a2)

display(a1 + a2)
display(a1 - a2)
display(a1 * a2)

# a1[řádek][sloupec]
print(a1[0][1])

# a1[řádek, sloupec] - speciální zápis v NumPy
print(a1[0, 1])

# [start:end:step]
# https://www.w3schools.com/python/numpy/numpy_array_slicing.asp

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

array([[1, 3, 3],
       [5, 5, 7],
       [7, 9, 9]])

array([[1, 1, 3],
       [3, 5, 5],
       [7, 7, 9]])

array([[0, 2, 0],
       [4, 0, 6],
       [0, 8, 0]])

2
2
[[4 5 6]]


In [34]:
b = np.array([1, 0, 10])
display(a1)
display(b)

# Při sčítání NumPy udělá z b vlastně 3 řádkovou matici.
display(a1 + b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([ 1,  0, 10])

array([[ 2,  2, 13],
       [ 5,  5, 16],
       [ 8,  8, 19]])

In [42]:
display(np.full((4, 4), 3.14))
display(np.zeros((4, 4), dtype="int8"))
display(np.ones((4, 4), dtype="int8"))
display(np.eye(4, dtype="int8"))
display(np.diag([1, 2, 3, 4]))

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])