In [1]:
import numpy as np

In [2]:
# 1D pole (vektor)
a = np.array([1, 2, 3], dtype="int32")
print(a)

[1 2 3]


In [3]:
# 2D pole (matice)
b = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    dtype="int32",
)
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# Dimenze matice
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Tvar matice (počet_řádků, počet_sloupců)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# Datový typ dat matice
print(a.dtype)
print(b.dtype)

int32
int32


In [7]:
# Počet prvků matice
print(a.size)
print(b.size)

3
6
