In [1]:
import numpy as np

In [7]:
a = np.array(
    [
        [1, 2, 3, 4, 5, 6, 7],
        [8, 9, 10, 11, 12, 13, 14],
    ]
)
print(a.shape)
print(a)

(2, 7)
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Přístup k prvkům - a[index_řádku, index_sloupce]
# Prvek na řádku s indexem 1, sloupce s indexem 2
print(a[0, 1])

2


In [21]:
# Přístup k řádkům - a[index_řádku], případně a[index_řádku, :]
print(a[0, :])
print(a[0])

print(a[1, :])
print(a[1])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]
[ 8  9 10 11 12 13 14]


In [23]:
# Přístup ke sloupcům - a[:, index_sloupce]
print(a[:, 0])
print(a[:, 1])

[1 8]
[2 9]
